name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Empty and append file
        run: |
          > vars.txt
          echo -n "run-test" >> vars.txt
          echo -n " suite" >> vars.txt
          echo -n " version" >> vars.txt

      - name: Read vars from file and set variables
        run: |
          echo "RUN_TEST=`cut -d" " -f1 vars.txt`" >> $GITHUB_ENV
          SUITE=`cut -d" " -f2 vars.txt`
          echo "SUITE=$SUITE" >> $GITHUB_ENV
          
      - name: Print vars
        run: |
          echo ${RUN_TEST}
          echo ${SUITE}
