name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Read vars from file and set variables
        run: |
          RUN_TEST=`cut -d" " -f1 vars.txt`
          echo $RUN_TEST
      
      - name: Print vars
        run: |
          echo ${RUN_TEST}
